@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "TaToolkit Storage" #F4F6F6{
Class "<<interface>>\nTaToolkitStorage" as TaToolkitStorage
Class JsonTaToolkitStorage
Class JsonSerializableTaToolkit
Class JsonAdaptedPerson
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TaToolkitStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TaToolkitStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTaToolkitStorage .up.|> TaToolkitStorage
JsonTaToolkitStorage ..> JsonSerializableTaToolkit
JsonSerializableTaToolkit --> "*" JsonAdaptedPerson

@enduml
