@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTaToolkit" as VersionedTaToolkit MODEL_COLOR
end box

[-> Model : undoTaToolkit()
activate Model

Model -> VersionedTaToolkit : undo()
activate VersionedTaToolkit

VersionedTaToolkit -> VersionedTaToolkit :resetData(ReadOnlyTaToolkit)
VersionedTaToolkit --> Model :
deactivate VersionedTaToolkit

[<-- Model
deactivate Model

@enduml
